const configured=window.TW_CONFIG&&!TW_CONFIG.SUPABASE_URL.includes('YOUR_')&&!TW_CONFIG.SUPABASE_ANON_KEY.includes('YOUR_');
const db=configured?supabase.createClient(TW_CONFIG.SUPABASE_URL,TW_CONFIG.SUPABASE_ANON_KEY):null;
let products=[],orders=[],editing=null;
const $=id=>document.getElementById(id);
function msg(t){$('toast').textContent=t;$('toast').style.display='block';setTimeout(()=>$('toast').style.display='none',2200)}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function wa(phone,text){return `https://wa.me/${String(phone).replace(/\D/g,'').replace(/^0/,'880')}?text=${encodeURIComponent(text)}`}
function orderId(o){return o.order_number||('TSW-'+new Date(o.created_at).toISOString().slice(0,10).replaceAll('-','')+'-'+String(o.id||'').replaceAll('-','').slice(0,6).toUpperCase())}
if(!db){$('setupMsg').textContent='প্রথমে config.js-এ Supabase URL ও public key বসান।';$('loginForm').querySelector('button').disabled=true}
$('loginForm').onsubmit=async e=>{e.preventDefault();if(!db)return;const {error}=await db.auth.signInWithPassword({email:$('email').value,password:$('password').value});if(error)return msg(error.message);showApp()};
$('logout').onclick=async()=>{if(db)await db.auth.signOut();location.reload()};
async function showApp(){const {data:{user}}=await db.auth.getUser();if(!user){$('loginCard').classList.remove('hidden');$('app').classList.add('hidden');return}$('loginCard').classList.add('hidden');$('app').classList.remove('hidden');await Promise.all([loadProducts(),loadOrders()])}
async function loadProducts(){const r=await db.from('products').select('*').order('created_at',{ascending:false});if(r.error)return msg(r.error.message);products=r.data||[];renderProducts()}
function renderProducts(){const q=$('search').value.toLowerCase();$('list').innerHTML=products.filter(p=>(p.name||'').toLowerCase().includes(q)).map(p=>`<div class="product"><img class="thumb" src="${p.image||'data:image/svg+xml,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100"><rect width="100%" height="100%" fill="#eef1f5"/><text x="50%" y="50%" text-anchor="middle">T-Shirt</text></svg>')}" onerror="this.style.opacity=.25"><div><b>${esc(p.name)}</b>${p.featured?'<span class="badge">Featured</span>':''}<div class="meta">৳${Number(p.price||0)} · ${esc(p.category||'')} · ${p.active?'Visible':'Hidden'}</div></div><div class="actions"><button onclick="editP('${p.id}')">Edit</button><button onclick="toggleP('${p.id}')">${p.active?'Hide':'Show'}</button><button class="danger" onclick="delP('${p.id}')">Delete</button></div></div>`).join('')||'<p>No products yet.</p>'}
window.editP=id=>{const p=products.find(x=>x.id===id);if(!p)return;editing=id;$('id').value=id;$('name').value=p.name||'';$('price').value=p.price||0;$('oldPrice').value=p.old_price||'';$('category').value=p.category||'';$('sizes').value=p.sizes||'';$('description').value=p.description||'';$('image').value=p.image||'';$('featured').checked=!!p.featured;$('active').checked=p.active!==false;$('formTitle').textContent='Edit Product';$('save').textContent='Save Changes';$('cancel').classList.remove('hidden');scrollTo({top:0,behavior:'smooth'})};
window.toggleP=async id=>{const p=products.find(x=>x.id===id);if(!p)return;const {error}=await db.from('products').update({active:!p.active}).eq('id',id);if(error)return msg(error.message);msg(p.active?'Product hidden':'Product visible');loadProducts()};
window.delP=async id=>{if(!confirm('এই product delete করবেন?'))return;const {error}=await db.from('products').delete().eq('id',id);if(error)return msg(error.message);msg('Deleted');loadProducts()};
$('productForm').onsubmit=async e=>{e.preventDefault();const p={name:$('name').value.trim(),price:Number($('price').value),old_price:Number($('oldPrice').value)||null,category:$('category').value.trim(),sizes:$('sizes').value.trim(),description:$('description').value.trim(),image:$('image').value.trim(),featured:$('featured').checked,active:$('active').checked};const r=editing?await db.from('products').update(p).eq('id',editing):await db.from('products').insert(p);if(r.error)return msg(r.error.message);msg(editing?'Updated':'Added');reset();loadProducts()};
function reset(){editing=null;$('productForm').reset();$('sizes').value='S, M, L, XL, XXL';$('active').checked=true;$('formTitle').textContent='নতুন Product';$('save').textContent='+ Add Product';$('cancel').classList.add('hidden')}$('cancel').onclick=reset;$('search').oninput=renderProducts;
async function loadOrders(){const r=await db.from('orders').select('*').order('created_at',{ascending:false}).limit(500);if(r.error){orders=[];$('ordersList').innerHTML='<div class="notice">'+esc(r.error.message)+'<br>আপনি কি <b>supabase-admin-upgrade.sql</b> Run করেছেন?</div>';$('migrationNotice').classList.remove('hidden');return}orders=r.data||[];$('migrationNotice').classList.add('hidden');renderOrders();renderStats();renderSummary()}
function filtered(){const q=$('orderSearch').value.toLowerCase(),st=$('statusFilter').value,pr=$('priorityFilter').value,df=$('dateFilter').value;const now=Date.now();return orders.filter(o=>{const hay=[orderId(o),o.name,o.phone,o.notes].join(' ').toLowerCase();if(q&&!hay.includes(q))return false;if(st&&(o.status||'Pending')!==st)return false;if(pr&&(o.priority||'Normal')!==pr)return false;if(df){const age=now-new Date(o.created_at).getTime();const days=df==='today'?1:Number(df);if(age>days*86400000)return false}return true})}
function statusClass(s){return String(s||'Pending').toLowerCase().replace(/[^a-z]/g,'')}
function renderOrders(){const data=filtered();$('ordersList').innerHTML=data.map(o=>{const st=o.status||'Pending',pr=o.priority||'Normal',total=Number(o.total||0);return `<div class="order"><div class="order-top"><div><div class="order-title">${esc(orderId(o))} <span class="badge ${statusClass(st)}">${esc(st)}</span>${pr==='Urgent'?'<span class="urgent"> 🔴 URGENT</span>':''}</div><b>${esc(o.name)}</b> · ${esc(o.phone)}<div class="meta">${esc(o.size||'')} × ${o.quantity||1} · ৳${total} · ${new Date(o.created_at).toLocaleString('en-BD')}</div></div><button class="ghost" onclick="viewOrder('${o.id}')">Details</button></div><div class="order-actions"><select onchange="changeStatus('${o.id}',this.value)">${['Pending','Confirmed','Processing','Ready','Shipped','Delivered','Cancelled','Returned'].map(x=>`<option ${x===st?'selected':''}>${x}</option>`).join('')}</select><select onchange="changePriority('${o.id}',this.value)">${['Urgent','Normal','Low'].map(x=>`<option ${x===pr?'selected':''}>${x}</option>`).join('')}</select><button class="whatsapp-btn" onclick="openWA('${o.phone}','${jsq(orderId(o))}')">WhatsApp</button><button onclick="markPaid('${o.id}')">✓ Paid</button></div></div>`}).join('')||'<p>No matching orders.</p>'}
function jsq(s=''){return String(s).replace(/\\/g,'\\\\').replace(/'/g,"\\'").replace(/\n/g,' ')}
window.openWA=(phone,id)=>window.open(wa(phone,`আসসালামু আলাইকুম। T-Shirt World থেকে আপনার order ${id} সম্পর্কে যোগাযোগ করছি।`),'_blank');
window.changeStatus=async(id,status)=>{const {error}=await db.from('orders').update({status}).eq('id',id);if(error)return handleDbError(error);msg('Status: '+status);loadOrders()};
window.changePriority=async(id,priority)=>{const {error}=await db.from('orders').update({priority}).eq('id',id);if(error)return handleDbError(error);msg('Priority updated');loadOrders()};
window.markPaid=async id=>{const {error}=await db.from('orders').update({payment_status:'Verified'}).eq('id',id);if(error)return handleDbError(error);msg('Payment marked verified');loadOrders()};
function handleDbError(e){if(String(e.message||'').includes('column')||String(e.code||'')==='42703'){$('migrationNotice').classList.remove('hidden');msg('আগে Supabase migration Run করুন')}else msg(e.message||'Update failed')}
window.viewOrder=id=>{const o=orders.find(x=>x.id===id);if(!o)return;const tx=(o.notes||'').match(/TxID:\s*([^|]+)/i)?.[1]||'Not found';$('orderDetails').innerHTML=`<div class="detail-grid"><div><b>Order ID</b><br>${esc(orderId(o))}</div><div><b>Status</b><br>${esc(o.status||'Pending')}</div><div><b>Customer</b><br>${esc(o.name)}</div><div><b>Phone</b><br>${esc(o.phone)}</div><div><b>Size / Qty</b><br>${esc(o.size||'')} × ${o.quantity||1}</div><div><b>Total</b><br>৳${Number(o.total||0)}</div><div><b>Payment</b><br>${esc(o.payment_status||'Unverified')}</div><div><b>TxID</b><br>${esc(tx)}</div><div><b>Delivery</b><br>${esc(o.delivery_area||((o.notes||'').includes('Rangpur City')?'Rangpur City':'Not specified'))}</div><div><b>Created</b><br>${new Date(o.created_at).toLocaleString('en-BD')}</div></div><div class="detail-note">${esc(o.notes||'No notes')}</div><div class="order-actions"><button class="primary" onclick="changeStatus('${o.id}','Confirmed');closeModal()">Confirm</button><button class="danger" onclick="changeStatus('${o.id}','Cancelled');closeModal()">Cancel</button><button class="whatsapp-btn" onclick="openWA('${o.phone}','${jsq(orderId(o))}')">WhatsApp</button></div>`;$('orderModal').classList.remove('hidden')};
function closeModal(){$('orderModal').classList.add('hidden')}$('closeModal').onclick=closeModal;$('orderModal').onclick=e=>{if(e.target===$('orderModal'))closeModal()};
function renderStats(){const count=s=>orders.filter(o=>(o.status||'Pending')===s).length;$('sTotal').textContent=orders.length;$('sPending').textContent=count('Pending');$('sConfirmed').textContent=count('Confirmed');$('sDelivered').textContent=count('Delivered');$('sCancelled').textContent=count('Cancelled');$('sSales').textContent='৳'+orders.filter(o=>(o.status||'Pending')!=='Cancelled').reduce((a,o)=>a+Number(o.total||0),0).toLocaleString('en-BD')}
function renderSummary(){const delivered=orders.filter(o=>(o.status||'Pending')==='Delivered'),qty=orders.reduce((a,o)=>a+Number(o.quantity||0),0),avg=orders.length?orders.reduce((a,o)=>a+Number(o.total||0),0)/orders.length:0;$('summaryText').innerHTML=`<div><b>Items Sold</b><br>${qty}</div><div><b>Delivered Sales</b><br>৳${delivered.reduce((a,o)=>a+Number(o.total||0),0).toLocaleString('en-BD')}</div><div><b>Average Order</b><br>৳${Math.round(avg).toLocaleString('en-BD')}</div>`}
function exportRows(){return filtered().map(o=>({Order_ID:orderId(o),Date:new Date(o.created_at).toLocaleString('en-BD'),Customer:o.name,Phone:o.phone,Size:o.size,Quantity:o.quantity,Total:o.total,Status:o.status||'Pending',Priority:o.priority||'Normal',Payment:o.payment_status||'Unverified',Delivery_Area:o.delivery_area||'',Notes:o.notes||''}))}
$('exportCsv').onclick=()=>{const rows=exportRows();if(!rows.length)return msg('No orders');const keys=Object.keys(rows[0]);const csv=[keys.join(','),...rows.map(r=>keys.map(k=>'"'+String(r[k]??'').replaceAll('"','""')+'"').join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='tshirt-world-orders.csv';a.click();msg('CSV downloaded — Google Sheets-এ import করতে পারবেন')};
$('exportXlsx').onclick=()=>{const rows=exportRows();if(!rows.length)return msg('No orders');if(!window.XLSX)return msg('Excel library loading হয়নি');const ws=XLSX.utils.json_to_sheet(rows),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Orders');XLSX.writeFile(wb,'tshirt-world-orders.xlsx');msg('Excel downloaded')};
$('orderSearch').oninput=renderOrders;$('statusFilter').onchange=renderOrders;$('priorityFilter').onchange=renderOrders;$('dateFilter').onchange=renderOrders;$('refreshOrders').onclick=loadOrders;$('refreshAll').onclick=()=>Promise.all([loadProducts(),loadOrders()]);
if(db)db.auth.getSession().then(({data})=>{if(data.session)showApp()});
