const configured=window.TW_CONFIG&&!TW_CONFIG.SUPABASE_URL.includes("YOUR_")&&!TW_CONFIG.SUPABASE_ANON_KEY.includes("YOUR_");
const db=configured?supabase.createClient(TW_CONFIG.SUPABASE_URL,TW_CONFIG.SUPABASE_ANON_KEY):null;
let products=[],editing=null;
const $=id=>document.getElementById(id);
function msg(t){$("toast").textContent=t;$("toast").style.display="block";setTimeout(()=>$("toast").style.display="none",1800)}
if(!db){$("setupMsg").textContent="প্রথমে config.js-এ Supabase URL ও anon key বসান।";$("loginForm").querySelector("button").disabled=true}
$("loginForm").onsubmit=async e=>{e.preventDefault();if(!db)return;const {error}=await db.auth.signInWithPassword({email:$("email").value,password:$("password").value});if(error)return msg(error.message);showApp()};
$("logout").onclick=async()=>{await db.auth.signOut();location.reload()};
async function showApp(){const {data:{user}}=await db.auth.getUser();if(!user){$("loginCard").classList.remove("hidden");$("app").classList.add("hidden");return}$("loginCard").classList.add("hidden");$("app").classList.remove("hidden");loadProducts();loadOrders()}
async function loadProducts(){const r=await db.from("products").select("*").order("created_at",{ascending:false});if(r.error)return msg(r.error.message);products=r.data||[];render()}
function render(){const q=$("search").value.toLowerCase();$("list").innerHTML=products.filter(p=>p.name.toLowerCase().includes(q)).map(p=>`<div class="product"><img class="thumb" src="${p.image||'data:image/svg+xml,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100"><rect width="100%" height="100%" fill="#eef1f5"/><text x="50%" y="50%" text-anchor="middle">T-Shirt</text></svg>')}"><div><b>${esc(p.name)}</b>${p.featured?'<span class="badge">Featured</span>':''}<div class="meta">৳${p.price} · ${esc(p.category||"")} · ${p.active?'Visible':'Hidden'}</div></div><div class="actions"><button onclick="editP('${p.id}')">Edit</button><button onclick="delP('${p.id}')">Delete</button></div></div>`).join("")||"<p>No products yet.</p>"}
window.editP=id=>{const p=products.find(x=>x.id===id);if(!p)return;editing=id;$("id").value=id;$("name").value=p.name;$("price").value=p.price;$("oldPrice").value=p.old_price||"";$("category").value=p.category||"";$("sizes").value=p.sizes||"";$("description").value=p.description||"";$("image").value=p.image||"";$("featured").checked=!!p.featured;$("active").checked=p.active!==false;$("formTitle").textContent="Edit Product";$("save").textContent="Save Changes";$("cancel").classList.remove("hidden")};
window.delP=async id=>{if(!confirm("এই product delete করবেন?"))return;const {error}=await db.from("products").delete().eq("id",id);if(error)return msg(error.message);msg("Deleted");loadProducts()};
$("productForm").onsubmit=async e=>{e.preventDefault();const p={name:$("name").value.trim(),price:Number($("price").value),old_price:Number($("oldPrice").value)||null,category:$("category").value.trim(),sizes:$("sizes").value.trim(),description:$("description").value.trim(),image:$("image").value.trim(),featured:$("featured").checked,active:$("active").checked};let r=editing?await db.from("products").update(p).eq("id",editing):await db.from("products").insert(p);if(r.error)return msg(r.error.message);msg(editing?"Updated":"Added");reset();loadProducts()};
function reset(){editing=null;$("productForm").reset();$("sizes").value="S, M, L, XL, XXL";$("active").checked=true;$("formTitle").textContent="নতুন Product";$("save").textContent="+ Add Product";$("cancel").classList.add("hidden")}
$("cancel").onclick=reset;$("search").oninput=render;
async function loadOrders(){const r=await db.from("orders").select("*").order("created_at",{ascending:false}).limit(30);if(r.error){$("ordersList").textContent=r.error.message;return}$("ordersList").innerHTML=(r.data||[]).map(o=>`<div class="order"><b>${esc(o.name)}</b> · ${esc(o.phone)} · Size ${esc(o.size)} × ${o.quantity}<br><span class="meta">৳${o.total||0} · ${new Date(o.created_at).toLocaleString()}</span><br>${esc(o.notes||"")}</div>`).join("")||"No orders yet."}
$("refreshOrders").onclick=loadOrders;
function esc(s=""){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
if(db)db.auth.getSession().then(({data})=>{if(data.session)showApp()});
